# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


# ruff: noqa: E402

# %% [markdown]
# # Mt Rhino
# TODO: top level description

# %% [markdown]
# ## Imports

import os

from ecoscope_workflows_core.tasks.config import set_string_var as set_string_var
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.io import (
    set_smart_connection as set_smart_connection,
)
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_table_widget_single_view as create_table_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.results import (
    merge_widget_views as merge_widget_views,
)
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_core.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_custom.tasks.io import (
    persist_df_wrapper as persist_df_wrapper,
)
from ecoscope_workflows_ext_custom.tasks.results import create_docx as create_docx
from ecoscope_workflows_ext_custom.tasks.transformation import (
    apply_sql_query as apply_sql_query,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    drop_column_prefix as drop_column_prefix,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    filter_row_values as filter_row_values,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df as summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    get_events_from_smart as get_events_from_smart,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    get_patrol_observations_from_smart as get_patrol_observations_from_smart,
)
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    create_point_layer as create_point_layer,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    create_polyline_layer as create_polyline_layer,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_bar_chart as draw_bar_chart,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_ecomap as draw_ecomap
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_table as draw_table
from ecoscope_workflows_ext_ecoscope.tasks.results import set_base_maps as set_base_maps
from ecoscope_workflows_ext_ecoscope.tasks.skip import (
    all_geometry_are_none as all_geometry_are_none,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_color_map as apply_color_map,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_reloc_coord_filter as apply_reloc_coord_filter,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    normalize_json_column as normalize_json_column,
)

# %% [markdown]
# ## Workflow Details

# %%
# parameters

workflow_details_params = dict(
    name=...,
    description=...,
    image_url=...,
)

# %%
# call the task


workflow_details = (
    set_workflow_details.set_task_instance_id("workflow_details")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**workflow_details_params)
    .call()
)


# %% [markdown]
# ## Time Range

# %%
# parameters

time_range_params = dict(
    since=...,
    until=...,
    timezone=...,
)

# %%
# call the task


time_range = (
    set_time_range.set_task_instance_id("time_range")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(time_format="%d %b %Y %H:%M:%S %Z", **time_range_params)
    .call()
)


# %% [markdown]
# ## Extract Timezone

# %%
# parameters

get_timezone_params = dict()

# %%
# call the task


get_timezone = (
    get_timezone_from_time_range.set_task_instance_id("get_timezone")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(time_range=time_range, **get_timezone_params)
    .call()
)


# %% [markdown]
# ## Data Source

# %%
# parameters

smart_client_name_params = dict(
    data_source=...,
)

# %%
# call the task


smart_client_name = (
    set_smart_connection.set_task_instance_id("smart_client_name")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**smart_client_name_params)
    .call()
)


# %% [markdown]
# ## Get Patrol Observations

# %%
# parameters

patrol_obs_params = dict()

# %%
# call the task


patrol_obs = (
    get_patrol_observations_from_smart.set_task_instance_id("patrol_obs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        client=smart_client_name,
        time_range=time_range,
        ca_uuid="735606d2-c34e-49c3-a45b-7496ca834e58",
        language_uuid="13451893-86af-4ec0-beac-2b8e0c2482b5",
        patrol_mandate=None,
        patrol_transport=None,
        **patrol_obs_params,
    )
    .call()
)


# %% [markdown]
# ## Convert Patrol Observations to Timezone

# %%
# parameters

convert_patrols_tz_params = dict()

# %%
# call the task


convert_patrols_tz = (
    convert_values_to_timezone.set_task_instance_id("convert_patrols_tz")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=patrol_obs,
        timezone=get_timezone,
        columns=["fixtime"],
        **convert_patrols_tz_params,
    )
    .call()
)


# %% [markdown]
# ## Remove Column Prefix (Observations)

# %%
# parameters

drop_prefix_obs_params = dict()

# %%
# call the task


drop_prefix_obs = (
    drop_column_prefix.set_task_instance_id("drop_prefix_obs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=convert_patrols_tz,
        prefix="extra__",
        duplicate_strategy="suffix",
        **drop_prefix_obs_params,
    )
    .call()
)


# %% [markdown]
# ## Filter Patrol Coordinates

# %%
# parameters

filter_patrol_coords_params = dict()

# %%
# call the task


filter_patrol_coords = (
    apply_reloc_coord_filter.set_task_instance_id("filter_patrol_coords")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=drop_prefix_obs,
        roi_gdf=None,
        roi_name=None,
        reset_index=False,
        bounding_box={"min_x": -180.0, "max_x": 180.0, "min_y": -90.0, "max_y": 90.0},
        filter_point_coords=[
            {"x": 180.0, "y": 90.0},
            {"x": 0.0, "y": 0.0},
            {"x": 1.0, "y": 1.0},
        ],
        **filter_patrol_coords_params,
    )
    .call()
)


# %% [markdown]
# ## Convert to Trajectories

# %%
# parameters

patrol_traj_params = dict(
    trajectory_segment_filter=...,
)

# %%
# call the task


patrol_traj = (
    relocations_to_trajectory.set_task_instance_id("patrol_traj")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(relocations=filter_patrol_coords, **patrol_traj_params)
    .call()
)


# %% [markdown]
# ## Remove Column Prefix (Trajectories)

# %%
# parameters

drop_prefix_traj_params = dict()

# %%
# call the task


drop_prefix_traj = (
    drop_column_prefix.set_task_instance_id("drop_prefix_traj")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=patrol_traj,
        prefix="extra__",
        duplicate_strategy="suffix",
        **drop_prefix_traj_params,
    )
    .call()
)


# %% [markdown]
# ## Clean Up Trajectory Columns

# %%
# parameters

cleanup_traj_cols_params = dict()

# %%
# call the task


cleanup_traj_cols = (
    map_columns.set_task_instance_id("cleanup_traj_cols")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=drop_prefix_traj,
        rename_columns={},
        drop_columns=["id", "track"],
        retain_columns=[],
        raise_if_not_found=False,
        **cleanup_traj_cols_params,
    )
    .call()
)


# %% [markdown]
# ## Filter Rhino Monitoring Patrols

# %%
# parameters

filter_rhino_patrols_params = dict()

# %%
# call the task


filter_rhino_patrols = (
    filter_row_values.set_task_instance_id("filter_rhino_patrols")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=cleanup_traj_cols,
        column="patrol_mandate",
        values=["Rhino Monitoring"],
        **filter_rhino_patrols_params,
    )
    .call()
)


# %% [markdown]
# ## Patrol Trajectory Colormap

# %%
# parameters

patrol_colormap_params = dict()

# %%
# call the task


patrol_colormap = (
    apply_color_map.set_task_instance_id("patrol_colormap")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=filter_rhino_patrols,
        input_column_name="station",
        output_column_name="patrol_colormap",
        colormap="Dark2",
        **patrol_colormap_params,
    )
    .call()
)


# %% [markdown]
# ## Get SMART Events

# %%
# parameters

smart_events_params = dict()

# %%
# call the task


smart_events = (
    get_events_from_smart.set_task_instance_id("smart_events")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        client=smart_client_name,
        time_range=time_range,
        ca_uuid="735606d2-c34e-49c3-a45b-7496ca834e58",
        language_uuid="13451893-86af-4ec0-beac-2b8e0c2482b5",
        **smart_events_params,
    )
    .call()
)


# %% [markdown]
# ## Convert Events to Timezone

# %%
# parameters

convert_events_tz_params = dict()

# %%
# call the task


convert_events_tz = (
    convert_values_to_timezone.set_task_instance_id("convert_events_tz")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=smart_events,
        timezone=get_timezone,
        columns=["time"],
        **convert_events_tz_params,
    )
    .call()
)


# %% [markdown]
# ## Filter Event Coordinates

# %%
# parameters

filter_event_coords_params = dict()

# %%
# call the task


filter_event_coords = (
    apply_reloc_coord_filter.set_task_instance_id("filter_event_coords")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=convert_events_tz,
        roi_gdf=None,
        roi_name=None,
        reset_index=False,
        bounding_box={"min_x": -180.0, "max_x": 180.0, "min_y": -90.0, "max_y": 90.0},
        filter_point_coords=[
            {"x": 180.0, "y": 90.0},
            {"x": 0.0, "y": 0.0},
            {"x": 1.0, "y": 1.0},
        ],
        **filter_event_coords_params,
    )
    .call()
)


# %% [markdown]
# ## Normalize Extracted Attributes

# %%
# parameters

normalize_attrs_params = dict()

# %%
# call the task


normalize_attrs = (
    normalize_json_column.set_task_instance_id("normalize_attrs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=filter_event_coords,
        column="extracted_attributes",
        skip_if_not_exists=True,
        sort_columns=True,
        **normalize_attrs_params,
    )
    .call()
)


# %% [markdown]
# ## Filter Rhino Sightings

# %%
# parameters

process_rhino_params = dict()

# %%
# call the task


process_rhino = (
    apply_sql_query.set_task_instance_id("process_rhino")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=normalize_attrs,
        columns=[
            "uuid",
            "event_type",
            "X",
            "Y",
            "time",
            "geometry",
            "extracted_attributes__Rhino Name",
        ],
        query='SELECT uuid, X, Y, time, geometry,\n  "extracted_attributes__Rhino Name" AS "Rhino Name"\nFROM df WHERE event_type = \'Rhino Direct Observation\'\n  AND "extracted_attributes__Rhino Name" IS NOT NULL',
        **process_rhino_params,
    )
    .call()
)


# %% [markdown]
# ## Rhino Sighting Colormap

# %%
# parameters

rhino_colormap_params = dict()

# %%
# call the task


rhino_colormap = (
    apply_color_map.set_task_instance_id("rhino_colormap")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=process_rhino,
        input_column_name="Rhino Name",
        output_column_name="rhino_colormap",
        colormap="Dark2",
        **rhino_colormap_params,
    )
    .call()
)


# %% [markdown]
# ## Persist Patrol Trajectories

# %%
# parameters

persist_patrol_traj_params = dict(
    filename=...,
)

# %%
# call the task


persist_patrol_traj = (
    persist_df_wrapper.set_task_instance_id("persist_patrol_traj")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        df=filter_rhino_patrols,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_prefix="rhino_patrol_trajectories",
        filetypes=["parquet"],
        sanitize=True,
        **persist_patrol_traj_params,
    )
    .call()
)


# %% [markdown]
# ## Persist Rhino Observations

# %%
# parameters

persist_rhino_obs_params = dict(
    filename=...,
)

# %%
# call the task


persist_rhino_obs = (
    persist_df_wrapper.set_task_instance_id("persist_rhino_obs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        df=process_rhino,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_prefix="rhino_observations",
        filetypes=["parquet"],
        sanitize=True,
        **persist_rhino_obs_params,
    )
    .call()
)


# %% [markdown]
# ## Base Maps

# %%
# parameters

base_map_defs_params = dict(
    base_maps=...,
)

# %%
# call the task


base_map_defs = (
    set_base_maps.set_task_instance_id("base_map_defs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**base_map_defs_params)
    .call()
)


# %% [markdown]
# ## Set Patrol Map Title

# %%
# parameters

set_patrol_map_title_params = dict()

# %%
# call the task


set_patrol_map_title = (
    set_string_var.set_task_instance_id("set_patrol_map_title")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(var="Rhino Patrol Trajectories", **set_patrol_map_title_params)
    .call()
)


# %% [markdown]
# ## Rename Trajectory Columns for Display

# %%
# parameters

rename_traj_cols_params = dict()

# %%
# call the task


rename_traj_cols = (
    map_columns.set_task_instance_id("rename_traj_cols")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=patrol_colormap,
        rename_columns={
            "segment_start": "Start Time",
            "timespan_seconds": "Duration (s)",
            "speed_kmhr": "Speed (kph)",
        },
        drop_columns=[],
        retain_columns=[],
        raise_if_not_found=False,
        **rename_traj_cols_params,
    )
    .call()
)


# %% [markdown]
# ## Create Patrol Polyline Layer

# %%
# parameters

patrol_polyline_params = dict(
    zoom=...,
)

# %%
# call the task


patrol_polyline = (
    create_polyline_layer.set_task_instance_id("patrol_polyline")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
            all_geometry_are_none,
        ],
        unpack_depth=1,
    )
    .partial(
        geodataframe=rename_traj_cols,
        layer_style={
            "get_width": 3,
            "width_units": "pixels",
            "color_column": "patrol_colormap",
        },
        legend={"label_column": "station", "color_column": "patrol_colormap"},
        tooltip_columns=["Start Time", "Duration (s)", "Speed (kph)"],
        **patrol_polyline_params,
    )
    .call()
)


# %% [markdown]
# ## Draw Patrol Ecomap

# %%
# parameters

patrol_ecomap_params = dict(
    view_state=...,
    widget_id=...,
)

# %%
# call the task


patrol_ecomap = (
    draw_ecomap.set_task_instance_id("patrol_ecomap")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        geo_layers=patrol_polyline,
        tile_layers=base_map_defs,
        north_arrow_style={"placement": "top-left"},
        legend_style={"title": "Station", "placement": "bottom-right"},
        static=False,
        title=None,
        max_zoom=20,
        **patrol_ecomap_params,
    )
    .call()
)


# %% [markdown]
# ## Persist Patrol Ecomap

# %%
# parameters

persist_patrol_ecomap_params = dict(
    filename=...,
)

# %%
# call the task


persist_patrol_ecomap = (
    persist_text.set_task_instance_id("persist_patrol_ecomap")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        text=patrol_ecomap,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="patrol_map",
        **persist_patrol_ecomap_params,
    )
    .call()
)


# %% [markdown]
# ## Create Patrol Map Widget

# %%
# parameters

patrol_map_widget_params = dict(
    view=...,
)

# %%
# call the task


patrol_map_widget = (
    create_map_widget_single_view.set_task_instance_id("patrol_map_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        title=set_patrol_map_title,
        data=persist_patrol_ecomap,
        **patrol_map_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Merge Patrol Map Widget

# %%
# parameters

merged_patrol_map_params = dict()

# %%
# call the task


merged_patrol_map = (
    merge_widget_views.set_task_instance_id("merged_patrol_map")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(widgets=[patrol_map_widget], **merged_patrol_map_params)
    .call()
)


# %% [markdown]
# ## Set Rhino Map Title

# %%
# parameters

set_rhino_map_title_params = dict()

# %%
# call the task


set_rhino_map_title = (
    set_string_var.set_task_instance_id("set_rhino_map_title")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(var="Rhino Sightings", **set_rhino_map_title_params)
    .call()
)


# %% [markdown]
# ## Create Rhino Point Layer

# %%
# parameters

rhino_point_layer_params = dict(
    zoom=...,
)

# %%
# call the task


rhino_point_layer = (
    create_point_layer.set_task_instance_id("rhino_point_layer")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
            all_geometry_are_none,
        ],
        unpack_depth=1,
    )
    .partial(
        geodataframe=rhino_colormap,
        layer_style={"get_radius": 5.0, "fill_color_column": "rhino_colormap"},
        legend={"label_column": "Rhino Name", "color_column": "rhino_colormap"},
        tooltip_columns=["Rhino Name", "time"],
        **rhino_point_layer_params,
    )
    .call()
)


# %% [markdown]
# ## Draw Rhino Ecomap

# %%
# parameters

rhino_ecomap_params = dict(
    view_state=...,
    widget_id=...,
)

# %%
# call the task


rhino_ecomap = (
    draw_ecomap.set_task_instance_id("rhino_ecomap")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        geo_layers=rhino_point_layer,
        tile_layers=base_map_defs,
        north_arrow_style={"placement": "top-left"},
        legend_style={"title": "Rhino Name", "placement": "bottom-right"},
        static=False,
        title=None,
        max_zoom=13,
        **rhino_ecomap_params,
    )
    .call()
)


# %% [markdown]
# ## Persist Rhino Ecomap

# %%
# parameters

persist_rhino_ecomap_params = dict(
    filename=...,
)

# %%
# call the task


persist_rhino_ecomap = (
    persist_text.set_task_instance_id("persist_rhino_ecomap")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        text=rhino_ecomap,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="rhino_map",
        **persist_rhino_ecomap_params,
    )
    .call()
)


# %% [markdown]
# ## Create Rhino Map Widget

# %%
# parameters

rhino_map_widget_params = dict(
    view=...,
)

# %%
# call the task


rhino_map_widget = (
    create_map_widget_single_view.set_task_instance_id("rhino_map_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        title=set_rhino_map_title, data=persist_rhino_ecomap, **rhino_map_widget_params
    )
    .call()
)


# %% [markdown]
# ## Merge Rhino Map Widget

# %%
# parameters

merged_rhino_map_params = dict()

# %%
# call the task


merged_rhino_map = (
    merge_widget_views.set_task_instance_id("merged_rhino_map")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(widgets=[rhino_map_widget], **merged_rhino_map_params)
    .call()
)


# %% [markdown]
# ## Summarize Rhino Sightings

# %%
# parameters

rhino_summary_params = dict()

# %%
# call the task


rhino_summary = (
    summarize_df.set_task_instance_id("rhino_summary")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=process_rhino,
        groupby_cols=["Rhino Name"],
        reset_index=True,
        summary_params=[
            {"display_name": "Count", "aggregator": "count", "column": "uuid"}
        ],
        **rhino_summary_params,
    )
    .call()
)


# %% [markdown]
# ## Persist Rhino Summary

# %%
# parameters

persist_summary_params = dict(
    filename=...,
)

# %%
# call the task


persist_summary = (
    persist_df_wrapper.set_task_instance_id("persist_summary")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        df=rhino_summary,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_prefix="rhino_summary",
        filetypes=["csv"],
        sanitize=False,
        **persist_summary_params,
    )
    .call()
)


# %% [markdown]
# ## Set Summary Table Title

# %%
# parameters

set_table_title_params = dict()

# %%
# call the task


set_table_title = (
    set_string_var.set_task_instance_id("set_table_title")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(var="Rhino Sighting Summary", **set_table_title_params)
    .call()
)


# %% [markdown]
# ## Draw Summary Table

# %%
# parameters

rhino_table_params = dict(
    widget_id=...,
)

# %%
# call the task


rhino_table = (
    draw_table.set_task_instance_id("rhino_table")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        dataframe=rhino_summary,
        columns=["Rhino Name", "Count"],
        table_config={
            "enable_sorting": True,
            "enable_filtering": True,
            "enable_download": True,
            "hide_header": False,
        },
        **rhino_table_params,
    )
    .call()
)


# %% [markdown]
# ## Persist Summary Table

# %%
# parameters

persist_table_params = dict(
    filename=...,
)

# %%
# call the task


persist_table = (
    persist_text.set_task_instance_id("persist_table")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        text=rhino_table,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="rhino_summary_table",
        **persist_table_params,
    )
    .call()
)


# %% [markdown]
# ## Create Summary Table Widget

# %%
# parameters

table_widget_params = dict(
    view=...,
)

# %%
# call the task


table_widget = (
    create_table_widget_single_view.set_task_instance_id("table_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(title=set_table_title, data=persist_table, **table_widget_params)
    .call()
)


# %% [markdown]
# ## Merge Summary Table Widget

# %%
# parameters

merged_table_widget_params = dict()

# %%
# call the task


merged_table_widget = (
    merge_widget_views.set_task_instance_id("merged_table_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(widgets=[table_widget], **merged_table_widget_params)
    .call()
)


# %% [markdown]
# ## Set Bar Chart Title

# %%
# parameters

set_bar_title_params = dict()

# %%
# call the task


set_bar_title = (
    set_string_var.set_task_instance_id("set_bar_title")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(var="Rhino Sighting Counts", **set_bar_title_params)
    .call()
)


# %% [markdown]
# ## Draw Rhino Bar Chart

# %%
# parameters

rhino_bar_params = dict(
    widget_id=...,
)

# %%
# call the task


rhino_bar = (
    draw_bar_chart.set_task_instance_id("rhino_bar")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        dataframe=rhino_summary,
        category="Rhino Name",
        layout_kwargs=None,
        bar_chart_configs=[
            {
                "label": "Count of Sightings",
                "column": "Count",
                "agg_func": "sum",
                "show_label": True,
                "style": {"marker_color": "#35b779"},
            }
        ],
        **rhino_bar_params,
    )
    .call()
)


# %% [markdown]
# ## Persist Bar Chart

# %%
# parameters

persist_bar_params = dict(
    filename=...,
)

# %%
# call the task


persist_bar = (
    persist_text.set_task_instance_id("persist_bar")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        text=rhino_bar,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="rhino_bar_chart",
        **persist_bar_params,
    )
    .call()
)


# %% [markdown]
# ## Create Bar Chart Widget

# %%
# parameters

bar_widget_params = dict(
    view=...,
)

# %%
# call the task


bar_widget = (
    create_plot_widget_single_view.set_task_instance_id("bar_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(title=set_bar_title, data=persist_bar, **bar_widget_params)
    .call()
)


# %% [markdown]
# ## Merge Bar Chart Widget

# %%
# parameters

merged_bar_widget_params = dict()

# %%
# call the task


merged_bar_widget = (
    merge_widget_views.set_task_instance_id("merged_bar_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(widgets=[bar_widget], **merged_bar_widget_params)
    .call()
)


# %% [markdown]
# ## Create Rhino Report

# %%
# parameters

rhino_report_params = dict(
    template_path=...,
)

# %%
# call the task


rhino_report = (
    create_docx.set_task_instance_id("rhino_report")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        context={
            "items": [
                {
                    "item_type": "timerange",
                    "key": "report_date",
                    "value": time_range,
                    "format": "%b %Y",
                },
                {
                    "item_type": "image",
                    "key": "patrol_map",
                    "value": persist_patrol_ecomap,
                    "screenshot_config": {
                        "wait_for_timeout": 20000,
                        "max_concurrent_pages": 2,
                        "device_scale_factor": 1.0,
                    },
                },
                {
                    "item_type": "image",
                    "key": "rhino_map",
                    "value": persist_rhino_ecomap,
                    "screenshot_config": {
                        "wait_for_timeout": 1000,
                        "max_concurrent_pages": 2,
                        "device_scale_factor": 1.0,
                    },
                },
                {"item_type": "table", "key": "rhino_summary", "value": rhino_summary},
                {
                    "item_type": "image",
                    "key": "bar_chart",
                    "value": persist_bar,
                    "screenshot_config": {
                        "wait_for_timeout": 0,
                        "max_concurrent_pages": 2,
                    },
                },
            ]
        },
        groupers=[],
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_prefix="mt_rhino_report",
        **rhino_report_params,
    )
    .call()
)


# %% [markdown]
# ## Create Dashboard

# %%
# parameters

dashboard_params = dict(
    warning=...,
)

# %%
# call the task


dashboard = (
    gather_dashboard.set_task_instance_id("dashboard")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        details=workflow_details,
        widgets=[
            merged_patrol_map,
            merged_rhino_map,
            merged_table_widget,
            merged_bar_widget,
        ],
        groupers=[],
        time_range=time_range,
        **dashboard_params,
    )
    .call()
)
