# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import json
import os

from ecoscope_workflows_core.graph import DependsOn, Graph, Node
from ecoscope_workflows_core.tasks.config import set_string_var as set_string_var
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.io import (
    set_smart_connection as set_smart_connection,
)
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_table_widget_single_view as create_table_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.results import (
    merge_widget_views as merge_widget_views,
)
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_core.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_custom.tasks.io import (
    persist_df_wrapper as persist_df_wrapper,
)
from ecoscope_workflows_ext_custom.tasks.results import create_docx as create_docx
from ecoscope_workflows_ext_custom.tasks.transformation import (
    apply_sql_query as apply_sql_query,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    drop_column_prefix as drop_column_prefix,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    filter_row_values as filter_row_values,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df as summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    get_events_from_smart as get_events_from_smart,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    get_patrol_observations_from_smart as get_patrol_observations_from_smart,
)
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    create_point_layer as create_point_layer,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    create_polyline_layer as create_polyline_layer,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_bar_chart as draw_bar_chart,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_ecomap as draw_ecomap
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_table as draw_table
from ecoscope_workflows_ext_ecoscope.tasks.results import set_base_maps as set_base_maps
from ecoscope_workflows_ext_ecoscope.tasks.skip import (
    all_geometry_are_none as all_geometry_are_none,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_color_map as apply_color_map,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_reloc_coord_filter as apply_reloc_coord_filter,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    normalize_json_column as normalize_json_column,
)

from ..params import Params


def main(params: Params):
    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    dependencies = {
        "workflow_details": [],
        "time_range": [],
        "get_timezone": ["time_range"],
        "smart_client_name": [],
        "patrol_obs": ["smart_client_name", "time_range"],
        "convert_patrols_tz": ["patrol_obs", "get_timezone"],
        "drop_prefix_obs": ["convert_patrols_tz"],
        "filter_patrol_coords": ["drop_prefix_obs"],
        "patrol_traj": ["filter_patrol_coords"],
        "drop_prefix_traj": ["patrol_traj"],
        "cleanup_traj_cols": ["drop_prefix_traj"],
        "filter_rhino_patrols": ["cleanup_traj_cols"],
        "patrol_colormap": ["filter_rhino_patrols"],
        "smart_events": ["smart_client_name", "time_range"],
        "convert_events_tz": ["smart_events", "get_timezone"],
        "filter_event_coords": ["convert_events_tz"],
        "normalize_attrs": ["filter_event_coords"],
        "process_rhino": ["normalize_attrs"],
        "rhino_colormap": ["process_rhino"],
        "persist_patrol_traj": ["filter_rhino_patrols"],
        "persist_rhino_obs": ["process_rhino"],
        "base_map_defs": [],
        "set_patrol_map_title": [],
        "rename_traj_cols": ["patrol_colormap"],
        "patrol_polyline": ["rename_traj_cols"],
        "patrol_ecomap": ["patrol_polyline", "base_map_defs"],
        "persist_patrol_ecomap": ["patrol_ecomap"],
        "patrol_map_widget": ["set_patrol_map_title", "persist_patrol_ecomap"],
        "merged_patrol_map": ["patrol_map_widget"],
        "set_rhino_map_title": [],
        "rhino_point_layer": ["rhino_colormap"],
        "rhino_ecomap": ["rhino_point_layer", "base_map_defs"],
        "persist_rhino_ecomap": ["rhino_ecomap"],
        "rhino_map_widget": ["set_rhino_map_title", "persist_rhino_ecomap"],
        "merged_rhino_map": ["rhino_map_widget"],
        "rhino_summary": ["process_rhino"],
        "persist_summary": ["rhino_summary"],
        "set_table_title": [],
        "rhino_table": ["rhino_summary"],
        "persist_table": ["rhino_table"],
        "table_widget": ["set_table_title", "persist_table"],
        "merged_table_widget": ["table_widget"],
        "set_bar_title": [],
        "rhino_bar": ["rhino_summary"],
        "persist_bar": ["rhino_bar"],
        "bar_widget": ["set_bar_title", "persist_bar"],
        "merged_bar_widget": ["bar_widget"],
        "rhino_report": [
            "time_range",
            "persist_patrol_ecomap",
            "persist_rhino_ecomap",
            "rhino_summary",
            "persist_bar",
        ],
        "dashboard": [
            "workflow_details",
            "merged_patrol_map",
            "merged_rhino_map",
            "merged_table_widget",
            "merged_bar_widget",
            "time_range",
        ],
    }

    nodes = {
        "workflow_details": Node(
            async_task=set_workflow_details.validate()
            .set_task_instance_id("workflow_details")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("workflow_details") or {}),
            method="call",
        ),
        "time_range": Node(
            async_task=set_time_range.validate()
            .set_task_instance_id("time_range")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_format": "%d %b %Y %H:%M:%S %Z",
            }
            | (params_dict.get("time_range") or {}),
            method="call",
        ),
        "get_timezone": Node(
            async_task=get_timezone_from_time_range.validate()
            .set_task_instance_id("get_timezone")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_range": DependsOn("time_range"),
            }
            | (params_dict.get("get_timezone") or {}),
            method="call",
        ),
        "smart_client_name": Node(
            async_task=set_smart_connection.validate()
            .set_task_instance_id("smart_client_name")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("smart_client_name") or {}),
            method="call",
        ),
        "patrol_obs": Node(
            async_task=get_patrol_observations_from_smart.validate()
            .set_task_instance_id("patrol_obs")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "client": DependsOn("smart_client_name"),
                "time_range": DependsOn("time_range"),
                "ca_uuid": "735606d2-c34e-49c3-a45b-7496ca834e58",
                "language_uuid": "13451893-86af-4ec0-beac-2b8e0c2482b5",
                "patrol_mandate": None,
                "patrol_transport": None,
            }
            | (params_dict.get("patrol_obs") or {}),
            method="call",
        ),
        "convert_patrols_tz": Node(
            async_task=convert_values_to_timezone.validate()
            .set_task_instance_id("convert_patrols_tz")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("patrol_obs"),
                "timezone": DependsOn("get_timezone"),
                "columns": [
                    "fixtime",
                ],
            }
            | (params_dict.get("convert_patrols_tz") or {}),
            method="call",
        ),
        "drop_prefix_obs": Node(
            async_task=drop_column_prefix.validate()
            .set_task_instance_id("drop_prefix_obs")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("convert_patrols_tz"),
                "prefix": "extra__",
                "duplicate_strategy": "suffix",
            }
            | (params_dict.get("drop_prefix_obs") or {}),
            method="call",
        ),
        "filter_patrol_coords": Node(
            async_task=apply_reloc_coord_filter.validate()
            .set_task_instance_id("filter_patrol_coords")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("drop_prefix_obs"),
                "roi_gdf": None,
                "roi_name": None,
                "reset_index": False,
                "bounding_box": {
                    "min_x": -180.0,
                    "max_x": 180.0,
                    "min_y": -90.0,
                    "max_y": 90.0,
                },
                "filter_point_coords": [
                    {
                        "x": 180.0,
                        "y": 90.0,
                    },
                    {
                        "x": 0.0,
                        "y": 0.0,
                    },
                    {
                        "x": 1.0,
                        "y": 1.0,
                    },
                ],
            }
            | (params_dict.get("filter_patrol_coords") or {}),
            method="call",
        ),
        "patrol_traj": Node(
            async_task=relocations_to_trajectory.validate()
            .set_task_instance_id("patrol_traj")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "relocations": DependsOn("filter_patrol_coords"),
            }
            | (params_dict.get("patrol_traj") or {}),
            method="call",
        ),
        "drop_prefix_traj": Node(
            async_task=drop_column_prefix.validate()
            .set_task_instance_id("drop_prefix_traj")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("patrol_traj"),
                "prefix": "extra__",
                "duplicate_strategy": "suffix",
            }
            | (params_dict.get("drop_prefix_traj") or {}),
            method="call",
        ),
        "cleanup_traj_cols": Node(
            async_task=map_columns.validate()
            .set_task_instance_id("cleanup_traj_cols")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("drop_prefix_traj"),
                "drop_columns": [
                    "id",
                    "track",
                ],
                "raise_if_not_found": False,
            }
            | (params_dict.get("cleanup_traj_cols") or {}),
            method="call",
        ),
        "filter_rhino_patrols": Node(
            async_task=filter_row_values.validate()
            .set_task_instance_id("filter_rhino_patrols")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("cleanup_traj_cols"),
                "column": "patrol_mandate",
                "values": [
                    "Rhino Monitoring",
                ],
            }
            | (params_dict.get("filter_rhino_patrols") or {}),
            method="call",
        ),
        "patrol_colormap": Node(
            async_task=apply_color_map.validate()
            .set_task_instance_id("patrol_colormap")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("filter_rhino_patrols"),
                "input_column_name": "station",
                "output_column_name": "patrol_colormap",
                "colormap": "Dark2",
            }
            | (params_dict.get("patrol_colormap") or {}),
            method="call",
        ),
        "smart_events": Node(
            async_task=get_events_from_smart.validate()
            .set_task_instance_id("smart_events")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "client": DependsOn("smart_client_name"),
                "time_range": DependsOn("time_range"),
                "ca_uuid": "735606d2-c34e-49c3-a45b-7496ca834e58",
                "language_uuid": "13451893-86af-4ec0-beac-2b8e0c2482b5",
            }
            | (params_dict.get("smart_events") or {}),
            method="call",
        ),
        "convert_events_tz": Node(
            async_task=convert_values_to_timezone.validate()
            .set_task_instance_id("convert_events_tz")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("smart_events"),
                "timezone": DependsOn("get_timezone"),
                "columns": [
                    "time",
                ],
            }
            | (params_dict.get("convert_events_tz") or {}),
            method="call",
        ),
        "filter_event_coords": Node(
            async_task=apply_reloc_coord_filter.validate()
            .set_task_instance_id("filter_event_coords")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("convert_events_tz"),
                "roi_gdf": None,
                "roi_name": None,
                "reset_index": False,
                "bounding_box": {
                    "min_x": -180.0,
                    "max_x": 180.0,
                    "min_y": -90.0,
                    "max_y": 90.0,
                },
                "filter_point_coords": [
                    {
                        "x": 180.0,
                        "y": 90.0,
                    },
                    {
                        "x": 0.0,
                        "y": 0.0,
                    },
                    {
                        "x": 1.0,
                        "y": 1.0,
                    },
                ],
            }
            | (params_dict.get("filter_event_coords") or {}),
            method="call",
        ),
        "normalize_attrs": Node(
            async_task=normalize_json_column.validate()
            .set_task_instance_id("normalize_attrs")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("filter_event_coords"),
                "column": "extracted_attributes",
                "skip_if_not_exists": True,
                "sort_columns": True,
            }
            | (params_dict.get("normalize_attrs") or {}),
            method="call",
        ),
        "process_rhino": Node(
            async_task=apply_sql_query.validate()
            .set_task_instance_id("process_rhino")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("normalize_attrs"),
                "columns": [
                    "uuid",
                    "event_type",
                    "X",
                    "Y",
                    "time",
                    "geometry",
                    "extracted_attributes__Rhino Name",
                ],
                "query": 'SELECT uuid, X, Y, time, geometry,\n  "extracted_attributes__Rhino Name" AS "Rhino Name"\nFROM df WHERE event_type = \'Rhino Direct Observation\'\n  AND "extracted_attributes__Rhino Name" IS NOT NULL',
            }
            | (params_dict.get("process_rhino") or {}),
            method="call",
        ),
        "rhino_colormap": Node(
            async_task=apply_color_map.validate()
            .set_task_instance_id("rhino_colormap")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("process_rhino"),
                "input_column_name": "Rhino Name",
                "output_column_name": "rhino_colormap",
                "colormap": "Dark2",
            }
            | (params_dict.get("rhino_colormap") or {}),
            method="call",
        ),
        "persist_patrol_traj": Node(
            async_task=persist_df_wrapper.validate()
            .set_task_instance_id("persist_patrol_traj")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("filter_rhino_patrols"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_prefix": "rhino_patrol_trajectories",
                "filetypes": [
                    "parquet",
                ],
                "sanitize": True,
            }
            | (params_dict.get("persist_patrol_traj") or {}),
            method="call",
        ),
        "persist_rhino_obs": Node(
            async_task=persist_df_wrapper.validate()
            .set_task_instance_id("persist_rhino_obs")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("process_rhino"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_prefix": "rhino_observations",
                "filetypes": [
                    "parquet",
                ],
                "sanitize": True,
            }
            | (params_dict.get("persist_rhino_obs") or {}),
            method="call",
        ),
        "base_map_defs": Node(
            async_task=set_base_maps.validate()
            .set_task_instance_id("base_map_defs")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("base_map_defs") or {}),
            method="call",
        ),
        "set_patrol_map_title": Node(
            async_task=set_string_var.validate()
            .set_task_instance_id("set_patrol_map_title")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "var": "Rhino Patrol Trajectories",
            }
            | (params_dict.get("set_patrol_map_title") or {}),
            method="call",
        ),
        "rename_traj_cols": Node(
            async_task=map_columns.validate()
            .set_task_instance_id("rename_traj_cols")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("patrol_colormap"),
                "rename_columns": {
                    "segment_start": "Start Time",
                    "timespan_seconds": "Duration (s)",
                    "speed_kmhr": "Speed (kph)",
                },
                "raise_if_not_found": False,
            }
            | (params_dict.get("rename_traj_cols") or {}),
            method="call",
        ),
        "patrol_polyline": Node(
            async_task=create_polyline_layer.validate()
            .set_task_instance_id("patrol_polyline")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                    all_geometry_are_none,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "geodataframe": DependsOn("rename_traj_cols"),
                "layer_style": {
                    "get_width": 3,
                    "width_units": "pixels",
                    "color_column": "patrol_colormap",
                },
                "legend": {
                    "label_column": "station",
                    "color_column": "patrol_colormap",
                },
                "tooltip_columns": [
                    "Start Time",
                    "Duration (s)",
                    "Speed (kph)",
                ],
            }
            | (params_dict.get("patrol_polyline") or {}),
            method="call",
        ),
        "patrol_ecomap": Node(
            async_task=draw_ecomap.validate()
            .set_task_instance_id("patrol_ecomap")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "geo_layers": DependsOn("patrol_polyline"),
                "tile_layers": DependsOn("base_map_defs"),
                "north_arrow_style": {
                    "placement": "top-left",
                },
                "legend_style": {
                    "title": "Station",
                    "placement": "bottom-right",
                },
                "static": False,
                "title": None,
                "max_zoom": 20,
            }
            | (params_dict.get("patrol_ecomap") or {}),
            method="call",
        ),
        "persist_patrol_ecomap": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_patrol_ecomap")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "text": DependsOn("patrol_ecomap"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "patrol_map",
            }
            | (params_dict.get("persist_patrol_ecomap") or {}),
            method="call",
        ),
        "patrol_map_widget": Node(
            async_task=create_map_widget_single_view.validate()
            .set_task_instance_id("patrol_map_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": DependsOn("set_patrol_map_title"),
                "data": DependsOn("persist_patrol_ecomap"),
            }
            | (params_dict.get("patrol_map_widget") or {}),
            method="call",
        ),
        "merged_patrol_map": Node(
            async_task=merge_widget_views.validate()
            .set_task_instance_id("merged_patrol_map")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "widgets": [
                    DependsOn("patrol_map_widget"),
                ],
            }
            | (params_dict.get("merged_patrol_map") or {}),
            method="call",
        ),
        "set_rhino_map_title": Node(
            async_task=set_string_var.validate()
            .set_task_instance_id("set_rhino_map_title")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "var": "Rhino Sightings",
            }
            | (params_dict.get("set_rhino_map_title") or {}),
            method="call",
        ),
        "rhino_point_layer": Node(
            async_task=create_point_layer.validate()
            .set_task_instance_id("rhino_point_layer")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                    all_geometry_are_none,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "geodataframe": DependsOn("rhino_colormap"),
                "layer_style": {
                    "get_radius": 5.0,
                    "fill_color_column": "rhino_colormap",
                },
                "legend": {
                    "label_column": "Rhino Name",
                    "color_column": "rhino_colormap",
                },
                "tooltip_columns": [
                    "Rhino Name",
                    "time",
                ],
            }
            | (params_dict.get("rhino_point_layer") or {}),
            method="call",
        ),
        "rhino_ecomap": Node(
            async_task=draw_ecomap.validate()
            .set_task_instance_id("rhino_ecomap")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "geo_layers": DependsOn("rhino_point_layer"),
                "tile_layers": DependsOn("base_map_defs"),
                "north_arrow_style": {
                    "placement": "top-left",
                },
                "legend_style": {
                    "title": "Rhino Name",
                    "placement": "bottom-right",
                },
                "static": False,
                "title": None,
                "max_zoom": 13,
            }
            | (params_dict.get("rhino_ecomap") or {}),
            method="call",
        ),
        "persist_rhino_ecomap": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_rhino_ecomap")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "text": DependsOn("rhino_ecomap"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "rhino_map",
            }
            | (params_dict.get("persist_rhino_ecomap") or {}),
            method="call",
        ),
        "rhino_map_widget": Node(
            async_task=create_map_widget_single_view.validate()
            .set_task_instance_id("rhino_map_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": DependsOn("set_rhino_map_title"),
                "data": DependsOn("persist_rhino_ecomap"),
            }
            | (params_dict.get("rhino_map_widget") or {}),
            method="call",
        ),
        "merged_rhino_map": Node(
            async_task=merge_widget_views.validate()
            .set_task_instance_id("merged_rhino_map")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "widgets": [
                    DependsOn("rhino_map_widget"),
                ],
            }
            | (params_dict.get("merged_rhino_map") or {}),
            method="call",
        ),
        "rhino_summary": Node(
            async_task=summarize_df.validate()
            .set_task_instance_id("rhino_summary")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("process_rhino"),
                "groupby_cols": [
                    "Rhino Name",
                ],
                "reset_index": True,
                "summary_params": [
                    {
                        "display_name": "Count",
                        "aggregator": "count",
                        "column": "uuid",
                    },
                ],
            }
            | (params_dict.get("rhino_summary") or {}),
            method="call",
        ),
        "persist_summary": Node(
            async_task=persist_df_wrapper.validate()
            .set_task_instance_id("persist_summary")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("rhino_summary"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_prefix": "rhino_summary",
                "filetypes": [
                    "csv",
                ],
                "sanitize": False,
            }
            | (params_dict.get("persist_summary") or {}),
            method="call",
        ),
        "set_table_title": Node(
            async_task=set_string_var.validate()
            .set_task_instance_id("set_table_title")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "var": "Rhino Sighting Summary",
            }
            | (params_dict.get("set_table_title") or {}),
            method="call",
        ),
        "rhino_table": Node(
            async_task=draw_table.validate()
            .set_task_instance_id("rhino_table")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "dataframe": DependsOn("rhino_summary"),
                "columns": [
                    "Rhino Name",
                    "Count",
                ],
                "table_config": {
                    "enable_sorting": True,
                    "enable_filtering": True,
                    "enable_download": True,
                    "hide_header": False,
                },
            }
            | (params_dict.get("rhino_table") or {}),
            method="call",
        ),
        "persist_table": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_table")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "text": DependsOn("rhino_table"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "rhino_summary_table",
            }
            | (params_dict.get("persist_table") or {}),
            method="call",
        ),
        "table_widget": Node(
            async_task=create_table_widget_single_view.validate()
            .set_task_instance_id("table_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": DependsOn("set_table_title"),
                "data": DependsOn("persist_table"),
            }
            | (params_dict.get("table_widget") or {}),
            method="call",
        ),
        "merged_table_widget": Node(
            async_task=merge_widget_views.validate()
            .set_task_instance_id("merged_table_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "widgets": [
                    DependsOn("table_widget"),
                ],
            }
            | (params_dict.get("merged_table_widget") or {}),
            method="call",
        ),
        "set_bar_title": Node(
            async_task=set_string_var.validate()
            .set_task_instance_id("set_bar_title")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "var": "Rhino Sighting Counts",
            }
            | (params_dict.get("set_bar_title") or {}),
            method="call",
        ),
        "rhino_bar": Node(
            async_task=draw_bar_chart.validate()
            .set_task_instance_id("rhino_bar")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "dataframe": DependsOn("rhino_summary"),
                "category": "Rhino Name",
                "layout_kwargs": None,
                "bar_chart_configs": [
                    {
                        "label": "Count of Sightings",
                        "column": "Count",
                        "agg_func": "sum",
                        "show_label": True,
                        "style": {
                            "marker_color": "#35b779",
                        },
                    },
                ],
            }
            | (params_dict.get("rhino_bar") or {}),
            method="call",
        ),
        "persist_bar": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_bar")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "text": DependsOn("rhino_bar"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "rhino_bar_chart",
            }
            | (params_dict.get("persist_bar") or {}),
            method="call",
        ),
        "bar_widget": Node(
            async_task=create_plot_widget_single_view.validate()
            .set_task_instance_id("bar_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": DependsOn("set_bar_title"),
                "data": DependsOn("persist_bar"),
            }
            | (params_dict.get("bar_widget") or {}),
            method="call",
        ),
        "merged_bar_widget": Node(
            async_task=merge_widget_views.validate()
            .set_task_instance_id("merged_bar_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "widgets": [
                    DependsOn("bar_widget"),
                ],
            }
            | (params_dict.get("merged_bar_widget") or {}),
            method="call",
        ),
        "rhino_report": Node(
            async_task=create_docx.validate()
            .set_task_instance_id("rhino_report")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "context": {
                    "items": [
                        {
                            "item_type": "timerange",
                            "key": "report_date",
                            "value": DependsOn("time_range"),
                            "format": "%b %Y",
                        },
                        {
                            "item_type": "image",
                            "key": "patrol_map",
                            "value": DependsOn("persist_patrol_ecomap"),
                            "screenshot_config": {
                                "wait_for_timeout": 20000,
                                "max_concurrent_pages": 2,
                                "device_scale_factor": 1.0,
                            },
                        },
                        {
                            "item_type": "image",
                            "key": "rhino_map",
                            "value": DependsOn("persist_rhino_ecomap"),
                            "screenshot_config": {
                                "wait_for_timeout": 1000,
                                "max_concurrent_pages": 2,
                                "device_scale_factor": 1.0,
                            },
                        },
                        {
                            "item_type": "table",
                            "key": "rhino_summary",
                            "value": DependsOn("rhino_summary"),
                        },
                        {
                            "item_type": "image",
                            "key": "bar_chart",
                            "value": DependsOn("persist_bar"),
                            "screenshot_config": {
                                "wait_for_timeout": 0,
                                "max_concurrent_pages": 2,
                            },
                        },
                    ],
                },
                "output_dir": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_prefix": "mt_rhino_report",
            }
            | (params_dict.get("rhino_report") or {}),
            method="call",
        ),
        "dashboard": Node(
            async_task=gather_dashboard.validate()
            .set_task_instance_id("dashboard")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "details": DependsOn("workflow_details"),
                "widgets": [
                    DependsOn("merged_patrol_map"),
                    DependsOn("merged_rhino_map"),
                    DependsOn("merged_table_widget"),
                    DependsOn("merged_bar_widget"),
                ],
                "time_range": DependsOn("time_range"),
            }
            | (params_dict.get("dashboard") or {}),
            method="call",
        ),
    }
    graph = Graph(dependencies=dependencies, nodes=nodes)
    results = graph.execute()
    return results
