# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import os
from typing import Any

from ecoscope.platform.tasks.analysis import summarize_df as summarize_df
from ecoscope.platform.tasks.config import set_string_var as set_string_var
from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.io import get_events as get_events
from ecoscope.platform.tasks.io import (
    get_patrol_observations_from_patrols_df_and_combined_params as get_patrol_observations_from_patrols_df_and_combined_params,
)
from ecoscope.platform.tasks.io import (
    get_patrols_from_combined_params as get_patrols_from_combined_params,
)
from ecoscope.platform.tasks.io import persist_df_wrapper as persist_df_wrapper
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.io import process_events_details as process_events_details
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.io import (
    set_patrols_and_patrol_events_params as set_patrols_and_patrol_events_params,
)
from ecoscope.platform.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope.platform.tasks.results import create_point_layer as create_point_layer
from ecoscope.platform.tasks.results import (
    create_polyline_layer as create_polyline_layer,
)
from ecoscope.platform.tasks.results import (
    create_table_widget_single_view as create_table_widget_single_view,
)
from ecoscope.platform.tasks.results import draw_chart as draw_chart
from ecoscope.platform.tasks.results import draw_ecomap as draw_ecomap
from ecoscope.platform.tasks.results import draw_table as draw_table
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.results import merge_widget_views as merge_widget_views
from ecoscope.platform.tasks.results import set_base_maps as set_base_maps
from ecoscope.platform.tasks.skip import all_geometry_are_none as all_geometry_are_none
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope.platform.tasks.skip import never as never
from ecoscope.platform.tasks.transformation import apply_color_map as apply_color_map
from ecoscope.platform.tasks.transformation import (
    apply_reloc_coord_filter as apply_reloc_coord_filter,
)
from ecoscope.platform.tasks.transformation import apply_sql_query as apply_sql_query
from ecoscope.platform.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope.platform.tasks.transformation import (
    drop_column_prefix as drop_column_prefix,
)
from ecoscope.platform.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_custom.tasks.results import create_docx as create_docx
from ecoscope_workflows_ext_custom.tasks.transformation import (
    filter_row_values as filter_row_values,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    merge_two_dataframes as merge_two_dataframes,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    pivot_dataframe as pivot_dataframe,
)
from wt_contracts import validate as _validate
from wt_task import task

from .. import metadata as _metadata


def main(params: dict[str, Any], validate_params_schema: bool = True):
    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_format="%d %b %Y %H:%M:%S %Z", **(params.get("time_range") or {}))
        .call()
    )

    get_timezone = (
        task(get_timezone_from_time_range)
        .validate()
        .set_task_instance_id("get_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params.get("get_timezone") or {}))
        .call()
    )

    er_client_name = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_client_name") or {}))
        .call()
    )

    er_patrol_params = (
        task(set_patrols_and_patrol_events_params)
        .validate()
        .set_task_instance_id("er_patrol_params")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            time_range=time_range,
            patrol_types=[
                "rhino_monitoring_patrol",
                "rhino_monitoring_vehicle_patrol",
                "rhino_monitor_patrol_reserve",
                "rhino_monitoring_veh_patrol_reserve",
            ],
            event_types=[],
            status=["done"],
            include_patrol_details=True,
            raise_on_empty=False,
            include_null_geometry=True,
            truncate_to_time_range=True,
            sub_page_size=100,
            patrols_overlap_daterange=True,
            **(params.get("er_patrol_params") or {}),
        )
        .call()
    )

    prefetch_patrols = (
        task(get_patrols_from_combined_params)
        .validate()
        .set_task_instance_id("prefetch_patrols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            combined_params=er_patrol_params, **(params.get("prefetch_patrols") or {})
        )
        .call()
    )

    patrol_obs = (
        task(get_patrol_observations_from_patrols_df_and_combined_params)
        .validate()
        .set_task_instance_id("patrol_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            patrols_df=prefetch_patrols,
            combined_params=er_patrol_params,
            **(params.get("patrol_obs") or {}),
        )
        .call()
    )

    convert_patrols_tz = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_patrols_tz")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_obs,
            timezone=get_timezone,
            columns=["fixtime", "patrol_start_time", "patrol_end_time"],
            **(params.get("convert_patrols_tz") or {}),
        )
        .call()
    )

    drop_prefix_obs = (
        task(drop_column_prefix)
        .validate()
        .set_task_instance_id("drop_prefix_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_patrols_tz,
            prefix="extra__",
            duplicate_strategy="suffix",
            **(params.get("drop_prefix_obs") or {}),
        )
        .call()
    )

    rename_patrol_cols = (
        task(map_columns)
        .validate()
        .set_task_instance_id("rename_patrol_cols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_prefix_obs,
            drop_columns=["patrol_type"],
            rename_columns={
                "patrol_type__value": "patrol_type",
                "patrol_type__display": "patrol_type_display",
            },
            retain_columns=[],
            raise_if_not_found=False,
            **(params.get("rename_patrol_cols") or {}),
        )
        .call()
    )

    filter_patrol_coords = (
        task(apply_reloc_coord_filter)
        .validate()
        .set_task_instance_id("filter_patrol_coords")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=rename_patrol_cols,
            roi_gdf=None,
            roi_name=None,
            reset_index=False,
            bounding_box={
                "min_x": -180.0,
                "max_x": 180.0,
                "min_y": -90.0,
                "max_y": 90.0,
            },
            filter_point_coords=[
                {"x": 180.0, "y": 90.0},
                {"x": 0.0, "y": 0.0},
                {"x": 1.0, "y": 1.0},
            ],
            **(params.get("filter_patrol_coords") or {}),
        )
        .call()
    )

    patrol_traj = (
        task(relocations_to_trajectory)
        .validate()
        .set_task_instance_id("patrol_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(relocations=filter_patrol_coords, **(params.get("patrol_traj") or {}))
        .call()
    )

    drop_prefix_traj = (
        task(drop_column_prefix)
        .validate()
        .set_task_instance_id("drop_prefix_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_traj,
            prefix="extra__",
            duplicate_strategy="suffix",
            **(params.get("drop_prefix_traj") or {}),
        )
        .call()
    )

    cleanup_traj_cols = (
        task(map_columns)
        .validate()
        .set_task_instance_id("cleanup_traj_cols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_prefix_traj,
            rename_columns={},
            drop_columns=["id", "track"],
            retain_columns=[],
            raise_if_not_found=False,
            **(params.get("cleanup_traj_cols") or {}),
        )
        .call()
    )

    patrol_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("patrol_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=cleanup_traj_cols,
            input_column_name="patrol_type_display",
            output_column_name="patrol_colormap",
            colormap="Dark2",
            **(params.get("patrol_colormap") or {}),
        )
        .call()
    )

    er_events = (
        task(get_events)
        .validate()
        .set_task_instance_id("er_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            time_range=time_range,
            event_types=["black_rhino_sighting_v202310"],
            event_columns=None,
            include_null_geometry=False,
            raise_on_empty=False,
            include_details=True,
            include_updates=False,
            include_related_events=False,
            include_display_values=True,
            force_point_geometry=True,
            **(params.get("er_events") or {}),
        )
        .call()
    )

    events_details = (
        task(process_events_details)
        .validate()
        .set_task_instance_id("events_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=er_events,
            client=er_client_name,
            map_to_titles=True,
            ordered=True,
            **(params.get("events_details") or {}),
        )
        .call()
    )

    convert_events_tz = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_events_tz")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_details,
            timezone=get_timezone,
            columns=["time"],
            **(params.get("convert_events_tz") or {}),
        )
        .call()
    )

    filter_event_coords = (
        task(apply_reloc_coord_filter)
        .validate()
        .set_task_instance_id("filter_event_coords")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_events_tz,
            roi_gdf=None,
            roi_name=None,
            reset_index=False,
            bounding_box={
                "min_x": -180.0,
                "max_x": 180.0,
                "min_y": -90.0,
                "max_y": 90.0,
            },
            filter_point_coords=[
                {"x": 180.0, "y": 90.0},
                {"x": 0.0, "y": 0.0},
                {"x": 1.0, "y": 1.0},
            ],
            **(params.get("filter_event_coords") or {}),
        )
        .call()
    )

    rhino_obs_long = (
        task(apply_sql_query)
        .validate()
        .set_task_instance_id("rhino_obs_long")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=filter_event_coords,
            sanitize=True,
            columns=None,
            query='SELECT * FROM (\n  SELECT df.id AS event_id, df.serial_number, df.time, df.geometry,\n    COALESCE(json_extract(j.value, \'$."Bull"\'), json_extract(j.value, \'$."Kifaru ID"\')) AS "Rhino Name",\n    COALESCE(json_extract(j.value, \'$."Sighting"\'), \'Unknown\') AS "Sighting Method"\n  FROM df, json_each(COALESCE(json_extract(df.event_details, \'$."Sighting Details - Bulls"\'), \'[]\')) AS j\n  UNION ALL\n  SELECT df.id AS event_id, df.serial_number, df.time, df.geometry,\n    COALESCE(json_extract(j.value, \'$."Known Cows"\'), json_extract(j.value, \'$."Kifaru ID"\')) AS "Rhino Name",\n    COALESCE(json_extract(j.value, \'$."Sighting"\'), \'Unknown\') AS "Sighting Method"\n  FROM df, json_each(COALESCE(json_extract(df.event_details, \'$."Sighting Details - Cows"\'), \'[]\')) AS j\n  UNION ALL\n  SELECT df.id AS event_id, df.serial_number, df.time, df.geometry,\n    COALESCE(json_extract(j.value, \'$."Unsexed Individual(s)"\'), json_extract(j.value, \'$."Kifaru ID"\')) AS "Rhino Name",\n    COALESCE(json_extract(j.value, \'$."Sighting"\'), \'Unknown\') AS "Sighting Method"\n  FROM df, json_each(COALESCE(json_extract(df.event_details, \'$."Sighting Details - Unsexed Individuals"\'), \'[]\')) AS j\n) WHERE "Rhino Name" IS NOT NULL',
            **(params.get("rhino_obs_long") or {}),
        )
        .call()
    )

    rhino_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("rhino_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=rhino_obs_long,
            input_column_name="Rhino Name",
            output_column_name="rhino_colormap",
            colormap="tab20b",
            **(params.get("rhino_colormap") or {}),
        )
        .call()
    )

    persist_patrol_traj = (
        task(persist_df_wrapper)
        .validate()
        .set_task_instance_id("persist_patrol_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            df=cleanup_traj_cols,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_prefix="rhino_patrol_trajectories",
            filetypes=["parquet"],
            sanitize=True,
            **(params.get("persist_patrol_traj") or {}),
        )
        .call()
    )

    persist_rhino_obs = (
        task(persist_df_wrapper)
        .validate()
        .set_task_instance_id("persist_rhino_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            df=rhino_obs_long,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_prefix="rhino_observations",
            filetypes=["parquet"],
            sanitize=True,
            **(params.get("persist_rhino_obs") or {}),
        )
        .call()
    )

    base_map_defs = (
        task(set_base_maps)
        .validate()
        .set_task_instance_id("base_map_defs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("base_map_defs") or {}))
        .call()
    )

    set_tri_map_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("set_tri_map_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            var="Mara Triangle Rhino Patrols", **(params.get("set_tri_map_title") or {})
        )
        .call()
    )

    filter_tri_traj = (
        task(filter_row_values)
        .validate()
        .set_task_instance_id("filter_tri_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_colormap,
            column="patrol_type",
            values=["rhino_monitoring_patrol", "rhino_monitoring_vehicle_patrol"],
            **(params.get("filter_tri_traj") or {}),
        )
        .call()
    )

    rename_tri_cols = (
        task(map_columns)
        .validate()
        .set_task_instance_id("rename_tri_cols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=filter_tri_traj,
            drop_columns=[],
            retain_columns=[],
            raise_if_not_found=False,
            rename_columns={
                "segment_start": "Start Time",
                "timespan_seconds": "Duration (s)",
                "speed_kmhr": "Speed (kph)",
            },
            **(params.get("rename_tri_cols") or {}),
        )
        .call()
    )

    tri_polyline = (
        task(create_polyline_layer)
        .validate()
        .set_task_instance_id("tri_polyline")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=rename_tri_cols,
            layer_style={
                "get_width": 3,
                "width_units": "pixels",
                "color_column": "patrol_colormap",
            },
            legend={
                "label_column": "patrol_type_display",
                "color_column": "patrol_colormap",
            },
            tooltip_columns=["Start Time", "Duration (s)", "Speed (kph)"],
            **(params.get("tri_polyline") or {}),
        )
        .call()
    )

    tri_ecomap = (
        task(draw_ecomap)
        .validate()
        .set_task_instance_id("tri_ecomap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geo_layers=tri_polyline,
            tile_layers=base_map_defs,
            north_arrow_style={"placement": "top-left"},
            legend_style={"title": "Patrol Type", "placement": "bottom-right"},
            static=False,
            title=None,
            max_zoom=20,
            **(params.get("tri_ecomap") or {}),
        )
        .call()
    )

    persist_tri_ecomap = (
        task(persist_text)
        .validate()
        .set_task_instance_id("persist_tri_ecomap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=tri_ecomap,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="triangle_patrol_map",
            **(params.get("persist_tri_ecomap") or {}),
        )
        .call()
    )

    tri_map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("tri_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title=set_tri_map_title,
            data=persist_tri_ecomap,
            **(params.get("tri_map_widget") or {}),
        )
        .call()
    )

    merged_tri_map = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("merged_tri_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(widgets=[tri_map_widget], **(params.get("merged_tri_map") or {}))
        .call()
    )

    set_res_map_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("set_res_map_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(var="Reserve Rhino Patrols", **(params.get("set_res_map_title") or {}))
        .call()
    )

    filter_res_traj = (
        task(filter_row_values)
        .validate()
        .set_task_instance_id("filter_res_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_colormap,
            column="patrol_type",
            values=[
                "rhino_monitor_patrol_reserve",
                "rhino_monitoring_veh_patrol_reserve",
            ],
            **(params.get("filter_res_traj") or {}),
        )
        .call()
    )

    rename_res_cols = (
        task(map_columns)
        .validate()
        .set_task_instance_id("rename_res_cols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=filter_res_traj,
            drop_columns=[],
            retain_columns=[],
            raise_if_not_found=False,
            rename_columns={
                "segment_start": "Start Time",
                "timespan_seconds": "Duration (s)",
                "speed_kmhr": "Speed (kph)",
            },
            **(params.get("rename_res_cols") or {}),
        )
        .call()
    )

    res_polyline = (
        task(create_polyline_layer)
        .validate()
        .set_task_instance_id("res_polyline")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=rename_res_cols,
            layer_style={
                "get_width": 3,
                "width_units": "pixels",
                "color_column": "patrol_colormap",
            },
            legend={
                "label_column": "patrol_type_display",
                "color_column": "patrol_colormap",
            },
            tooltip_columns=["Start Time", "Duration (s)", "Speed (kph)"],
            **(params.get("res_polyline") or {}),
        )
        .call()
    )

    res_ecomap = (
        task(draw_ecomap)
        .validate()
        .set_task_instance_id("res_ecomap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geo_layers=res_polyline,
            tile_layers=base_map_defs,
            north_arrow_style={"placement": "top-left"},
            legend_style={"title": "Patrol Type", "placement": "bottom-right"},
            static=False,
            title=None,
            max_zoom=20,
            **(params.get("res_ecomap") or {}),
        )
        .call()
    )

    persist_res_ecomap = (
        task(persist_text)
        .validate()
        .set_task_instance_id("persist_res_ecomap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=res_ecomap,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="reserve_patrol_map",
            **(params.get("persist_res_ecomap") or {}),
        )
        .call()
    )

    res_map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("res_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title=set_res_map_title,
            data=persist_res_ecomap,
            **(params.get("res_map_widget") or {}),
        )
        .call()
    )

    merged_res_map = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("merged_res_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(widgets=[res_map_widget], **(params.get("merged_res_map") or {}))
        .call()
    )

    set_rhino_map_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("set_rhino_map_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(var="Rhino Sightings", **(params.get("set_rhino_map_title") or {}))
        .call()
    )

    rhino_point_layer = (
        task(create_point_layer)
        .validate()
        .set_task_instance_id("rhino_point_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=rhino_colormap,
            layer_style={"get_radius": 5.0, "fill_color_column": "rhino_colormap"},
            legend={"label_column": "Rhino Name", "color_column": "rhino_colormap"},
            tooltip_columns=["Rhino Name", "Sighting Method", "time"],
            **(params.get("rhino_point_layer") or {}),
        )
        .call()
    )

    rhino_ecomap = (
        task(draw_ecomap)
        .validate()
        .set_task_instance_id("rhino_ecomap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geo_layers=rhino_point_layer,
            tile_layers=base_map_defs,
            north_arrow_style={"placement": "top-left"},
            legend_style={"title": "Rhino", "placement": "bottom-right"},
            static=False,
            title=None,
            max_zoom=13,
            **(params.get("rhino_ecomap") or {}),
        )
        .call()
    )

    persist_rhino_ecomap = (
        task(persist_text)
        .validate()
        .set_task_instance_id("persist_rhino_ecomap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=rhino_ecomap,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="rhino_map",
            **(params.get("persist_rhino_ecomap") or {}),
        )
        .call()
    )

    rhino_map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("rhino_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title=set_rhino_map_title,
            data=persist_rhino_ecomap,
            **(params.get("rhino_map_widget") or {}),
        )
        .call()
    )

    merged_rhino_map = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("merged_rhino_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(widgets=[rhino_map_widget], **(params.get("merged_rhino_map") or {}))
        .call()
    )

    method_counts = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("method_counts")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=rhino_obs_long,
            groupby_cols=["Rhino Name", "Sighting Method"],
            reset_index=True,
            summary_params=[
                {"display_name": "Count", "aggregator": "count", "column": "event_id"}
            ],
            **(params.get("method_counts") or {}),
        )
        .call()
    )

    method_pivot = (
        task(pivot_dataframe)
        .validate()
        .set_task_instance_id("method_pivot")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=method_counts,
            index="Rhino Name",
            columns="Sighting Method",
            values="Count",
            fill_value=0,
            **(params.get("method_pivot") or {}),
        )
        .call()
    )

    rhino_totals = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("rhino_totals")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=rhino_obs_long,
            groupby_cols=["Rhino Name"],
            reset_index=True,
            summary_params=[
                {"display_name": "Total", "aggregator": "count", "column": "event_id"}
            ],
            **(params.get("rhino_totals") or {}),
        )
        .call()
    )

    rhino_summary = (
        task(merge_two_dataframes)
        .validate()
        .set_task_instance_id("rhino_summary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            left=method_pivot,
            right=rhino_totals,
            how="left",
            on="Rhino Name",
            fillna_value=0,
            **(params.get("rhino_summary") or {}),
        )
        .call()
    )

    persist_summary = (
        task(persist_df_wrapper)
        .validate()
        .set_task_instance_id("persist_summary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            df=rhino_summary,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_prefix="rhino_summary",
            filetypes=["csv"],
            sanitize=False,
            **(params.get("persist_summary") or {}),
        )
        .call()
    )

    set_table_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("set_table_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(var="Rhino Sighting Summary", **(params.get("set_table_title") or {}))
        .call()
    )

    rhino_table = (
        task(draw_table)
        .validate()
        .set_task_instance_id("rhino_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=rhino_summary,
            columns=None,
            table_config={
                "enable_sorting": True,
                "enable_filtering": True,
                "enable_download": True,
                "hide_header": False,
            },
            **(params.get("rhino_table") or {}),
        )
        .call()
    )

    persist_table = (
        task(persist_text)
        .validate()
        .set_task_instance_id("persist_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=rhino_table,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="rhino_summary_table",
            **(params.get("persist_table") or {}),
        )
        .call()
    )

    table_widget = (
        task(create_table_widget_single_view)
        .validate()
        .set_task_instance_id("table_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title=set_table_title,
            data=persist_table,
            **(params.get("table_widget") or {}),
        )
        .call()
    )

    merged_table_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("merged_table_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(widgets=[table_widget], **(params.get("merged_table_widget") or {}))
        .call()
    )

    set_bar_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("set_bar_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(var="Rhino Sightings by Method", **(params.get("set_bar_title") or {}))
        .call()
    )

    rhino_bar = (
        task(draw_chart)
        .validate()
        .set_task_instance_id("rhino_bar")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=rhino_obs_long,
            x_axis="Rhino Name",
            figures=[
                {
                    "metric": {
                        "display_name": "Sightings",
                        "aggregator": "count",
                        "column": "event_id",
                    },
                    "chart_type": "bar",
                }
            ],
            category="Sighting Method",
            barmode="stack",
            palette="Dark2",
            layout_style={
                "showlegend": True,
                "legend_title": "Sighting Method",
                "yaxis": {"title": "Sightings"},
            },
            **(params.get("rhino_bar") or {}),
        )
        .call()
    )

    persist_bar = (
        task(persist_text)
        .validate()
        .set_task_instance_id("persist_bar")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=rhino_bar,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="rhino_bar_chart",
            **(params.get("persist_bar") or {}),
        )
        .call()
    )

    bar_widget = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("bar_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title=set_bar_title, data=persist_bar, **(params.get("bar_widget") or {})
        )
        .call()
    )

    merged_bar_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("merged_bar_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(widgets=[bar_widget], **(params.get("merged_bar_widget") or {}))
        .call()
    )

    rhino_report = (
        task(create_docx)
        .validate()
        .set_task_instance_id("rhino_report")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            context={
                "items": [
                    {
                        "item_type": "timerange",
                        "key": "report_date",
                        "value": time_range,
                        "format": "%b %Y",
                    },
                    {
                        "item_type": "image",
                        "key": "patrol_map_triangle",
                        "value": persist_tri_ecomap,
                        "screenshot_config": {
                            "wait_for_timeout": 20000,
                            "max_concurrent_pages": 2,
                            "device_scale_factor": 1.0,
                        },
                    },
                    {
                        "item_type": "image",
                        "key": "patrol_map_reserve",
                        "value": persist_res_ecomap,
                        "screenshot_config": {
                            "wait_for_timeout": 20000,
                            "max_concurrent_pages": 2,
                            "device_scale_factor": 1.0,
                        },
                    },
                    {
                        "item_type": "image",
                        "key": "rhino_map",
                        "value": persist_rhino_ecomap,
                        "screenshot_config": {
                            "wait_for_timeout": 1000,
                            "max_concurrent_pages": 2,
                            "device_scale_factor": 1.0,
                        },
                    },
                    {
                        "item_type": "table",
                        "key": "rhino_summary",
                        "value": rhino_summary,
                    },
                    {
                        "item_type": "image",
                        "key": "bar_chart",
                        "value": persist_bar,
                        "screenshot_config": {
                            "wait_for_timeout": 0,
                            "max_concurrent_pages": 2,
                        },
                    },
                ]
            },
            groupers=[],
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_prefix="mt_rhino_report",
            **(params.get("rhino_report") or {}),
        )
        .call()
    )

    dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[
                merged_tri_map,
                merged_res_map,
                merged_rhino_map,
                merged_table_widget,
                merged_bar_widget,
            ],
            groupers=[],
            time_range=time_range,
            **(params.get("dashboard") or {}),
        )
        .call()
    )

    return dashboard
