# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import os
from typing import Any

from ecoscope.platform.tasks.analysis import summarize_df as summarize_df
from ecoscope.platform.tasks.config import set_string_var as set_string_var
from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.io import get_events_from_smart as get_events_from_smart
from ecoscope.platform.tasks.io import (
    get_patrol_observations_from_smart as get_patrol_observations_from_smart,
)
from ecoscope.platform.tasks.io import persist_df_wrapper as persist_df_wrapper
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.io import set_smart_connection as set_smart_connection
from ecoscope.platform.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope.platform.tasks.results import create_point_layer as create_point_layer
from ecoscope.platform.tasks.results import (
    create_polyline_layer as create_polyline_layer,
)
from ecoscope.platform.tasks.results import (
    create_table_widget_single_view as create_table_widget_single_view,
)
from ecoscope.platform.tasks.results import draw_bar_chart as draw_bar_chart
from ecoscope.platform.tasks.results import draw_ecomap as draw_ecomap
from ecoscope.platform.tasks.results import draw_table as draw_table
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.results import merge_widget_views as merge_widget_views
from ecoscope.platform.tasks.results import set_base_maps as set_base_maps
from ecoscope.platform.tasks.skip import all_geometry_are_none as all_geometry_are_none
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope.platform.tasks.skip import never as never
from ecoscope.platform.tasks.transformation import apply_color_map as apply_color_map
from ecoscope.platform.tasks.transformation import (
    apply_reloc_coord_filter as apply_reloc_coord_filter,
)
from ecoscope.platform.tasks.transformation import apply_sql_query as apply_sql_query
from ecoscope.platform.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope.platform.tasks.transformation import (
    drop_column_prefix as drop_column_prefix,
)
from ecoscope.platform.tasks.transformation import map_columns as map_columns
from ecoscope.platform.tasks.transformation import (
    normalize_json_column as normalize_json_column,
)
from ecoscope_workflows_ext_custom.tasks.results import create_docx as create_docx
from ecoscope_workflows_ext_custom.tasks.transformation import (
    filter_row_values as filter_row_values,
)
from wt_contracts import validate as _validate
from wt_task import task

from .. import metadata as _metadata


def main(params: dict[str, Any], validate_params_schema: bool = True):
    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_format="%d %b %Y %H:%M:%S %Z", **(params.get("time_range") or {}))
        .call()
    )

    get_timezone = (
        task(get_timezone_from_time_range)
        .validate()
        .set_task_instance_id("get_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params.get("get_timezone") or {}))
        .call()
    )

    smart_client_name = (
        task(set_smart_connection)
        .validate()
        .set_task_instance_id("smart_client_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("smart_client_name") or {}))
        .call()
    )

    patrol_obs = (
        task(get_patrol_observations_from_smart)
        .validate()
        .set_task_instance_id("patrol_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=smart_client_name,
            time_range=time_range,
            ca_uuid="735606d2-c34e-49c3-a45b-7496ca834e58",
            language_uuid="13451893-86af-4ec0-beac-2b8e0c2482b5",
            patrol_mandate=None,
            patrol_transport=None,
            **(params.get("patrol_obs") or {}),
        )
        .call()
    )

    convert_patrols_tz = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_patrols_tz")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_obs,
            timezone=get_timezone,
            columns=["fixtime"],
            **(params.get("convert_patrols_tz") or {}),
        )
        .call()
    )

    drop_prefix_obs = (
        task(drop_column_prefix)
        .validate()
        .set_task_instance_id("drop_prefix_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_patrols_tz,
            prefix="extra__",
            duplicate_strategy="suffix",
            **(params.get("drop_prefix_obs") or {}),
        )
        .call()
    )

    filter_patrol_coords = (
        task(apply_reloc_coord_filter)
        .validate()
        .set_task_instance_id("filter_patrol_coords")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_prefix_obs,
            roi_gdf=None,
            roi_name=None,
            reset_index=False,
            bounding_box={
                "min_x": -180.0,
                "max_x": 180.0,
                "min_y": -90.0,
                "max_y": 90.0,
            },
            filter_point_coords=[
                {"x": 180.0, "y": 90.0},
                {"x": 0.0, "y": 0.0},
                {"x": 1.0, "y": 1.0},
            ],
            **(params.get("filter_patrol_coords") or {}),
        )
        .call()
    )

    patrol_traj = (
        task(relocations_to_trajectory)
        .validate()
        .set_task_instance_id("patrol_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(relocations=filter_patrol_coords, **(params.get("patrol_traj") or {}))
        .call()
    )

    drop_prefix_traj = (
        task(drop_column_prefix)
        .validate()
        .set_task_instance_id("drop_prefix_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_traj,
            prefix="extra__",
            duplicate_strategy="suffix",
            **(params.get("drop_prefix_traj") or {}),
        )
        .call()
    )

    cleanup_traj_cols = (
        task(map_columns)
        .validate()
        .set_task_instance_id("cleanup_traj_cols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_prefix_traj,
            rename_columns={},
            drop_columns=["id", "track"],
            retain_columns=[],
            raise_if_not_found=False,
            **(params.get("cleanup_traj_cols") or {}),
        )
        .call()
    )

    filter_rhino_patrols = (
        task(filter_row_values)
        .validate()
        .set_task_instance_id("filter_rhino_patrols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=cleanup_traj_cols,
            column="patrol_mandate",
            values=["Rhino Monitoring"],
            **(params.get("filter_rhino_patrols") or {}),
        )
        .call()
    )

    patrol_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("patrol_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=filter_rhino_patrols,
            input_column_name="station",
            output_column_name="patrol_colormap",
            colormap="Dark2",
            **(params.get("patrol_colormap") or {}),
        )
        .call()
    )

    smart_events = (
        task(get_events_from_smart)
        .validate()
        .set_task_instance_id("smart_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=smart_client_name,
            time_range=time_range,
            ca_uuid="735606d2-c34e-49c3-a45b-7496ca834e58",
            language_uuid="13451893-86af-4ec0-beac-2b8e0c2482b5",
            **(params.get("smart_events") or {}),
        )
        .call()
    )

    convert_events_tz = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_events_tz")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=smart_events,
            timezone=get_timezone,
            columns=["time"],
            **(params.get("convert_events_tz") or {}),
        )
        .call()
    )

    filter_event_coords = (
        task(apply_reloc_coord_filter)
        .validate()
        .set_task_instance_id("filter_event_coords")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_events_tz,
            roi_gdf=None,
            roi_name=None,
            reset_index=False,
            bounding_box={
                "min_x": -180.0,
                "max_x": 180.0,
                "min_y": -90.0,
                "max_y": 90.0,
            },
            filter_point_coords=[
                {"x": 180.0, "y": 90.0},
                {"x": 0.0, "y": 0.0},
                {"x": 1.0, "y": 1.0},
            ],
            **(params.get("filter_event_coords") or {}),
        )
        .call()
    )

    normalize_attrs = (
        task(normalize_json_column)
        .validate()
        .set_task_instance_id("normalize_attrs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=filter_event_coords,
            column="extracted_attributes",
            skip_if_not_exists=True,
            sort_columns=True,
            **(params.get("normalize_attrs") or {}),
        )
        .call()
    )

    process_rhino = (
        task(apply_sql_query)
        .validate()
        .set_task_instance_id("process_rhino")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=normalize_attrs,
            columns=[
                "uuid",
                "event_type",
                "X",
                "Y",
                "time",
                "geometry",
                "extracted_attributes__Rhino Name",
            ],
            query='SELECT uuid, X, Y, time, geometry,\n  "extracted_attributes__Rhino Name" AS "Rhino Name"\nFROM df WHERE event_type = \'Rhino Direct Observation\'\n  AND "extracted_attributes__Rhino Name" IS NOT NULL',
            **(params.get("process_rhino") or {}),
        )
        .call()
    )

    rhino_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("rhino_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=process_rhino,
            input_column_name="Rhino Name",
            output_column_name="rhino_colormap",
            colormap="Dark2",
            **(params.get("rhino_colormap") or {}),
        )
        .call()
    )

    persist_patrol_traj = (
        task(persist_df_wrapper)
        .validate()
        .set_task_instance_id("persist_patrol_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            df=filter_rhino_patrols,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_prefix="rhino_patrol_trajectories",
            filetypes=["parquet"],
            sanitize=True,
            **(params.get("persist_patrol_traj") or {}),
        )
        .call()
    )

    persist_rhino_obs = (
        task(persist_df_wrapper)
        .validate()
        .set_task_instance_id("persist_rhino_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            df=process_rhino,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_prefix="rhino_observations",
            filetypes=["parquet"],
            sanitize=True,
            **(params.get("persist_rhino_obs") or {}),
        )
        .call()
    )

    base_map_defs = (
        task(set_base_maps)
        .validate()
        .set_task_instance_id("base_map_defs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("base_map_defs") or {}))
        .call()
    )

    set_patrol_map_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("set_patrol_map_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            var="Rhino Patrol Trajectories",
            **(params.get("set_patrol_map_title") or {}),
        )
        .call()
    )

    rename_traj_cols = (
        task(map_columns)
        .validate()
        .set_task_instance_id("rename_traj_cols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_colormap,
            rename_columns={
                "segment_start": "Start Time",
                "timespan_seconds": "Duration (s)",
                "speed_kmhr": "Speed (kph)",
            },
            drop_columns=[],
            retain_columns=[],
            raise_if_not_found=False,
            **(params.get("rename_traj_cols") or {}),
        )
        .call()
    )

    patrol_polyline = (
        task(create_polyline_layer)
        .validate()
        .set_task_instance_id("patrol_polyline")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=rename_traj_cols,
            layer_style={
                "get_width": 3,
                "width_units": "pixels",
                "color_column": "patrol_colormap",
            },
            legend={"label_column": "station", "color_column": "patrol_colormap"},
            tooltip_columns=["Start Time", "Duration (s)", "Speed (kph)"],
            **(params.get("patrol_polyline") or {}),
        )
        .call()
    )

    patrol_ecomap = (
        task(draw_ecomap)
        .validate()
        .set_task_instance_id("patrol_ecomap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geo_layers=patrol_polyline,
            tile_layers=base_map_defs,
            north_arrow_style={"placement": "top-left"},
            legend_style={"title": "Station", "placement": "bottom-right"},
            static=False,
            title=None,
            max_zoom=20,
            **(params.get("patrol_ecomap") or {}),
        )
        .call()
    )

    persist_patrol_ecomap = (
        task(persist_text)
        .validate()
        .set_task_instance_id("persist_patrol_ecomap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=patrol_ecomap,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="patrol_map",
            **(params.get("persist_patrol_ecomap") or {}),
        )
        .call()
    )

    patrol_map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("patrol_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title=set_patrol_map_title,
            data=persist_patrol_ecomap,
            **(params.get("patrol_map_widget") or {}),
        )
        .call()
    )

    merged_patrol_map = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("merged_patrol_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(widgets=[patrol_map_widget], **(params.get("merged_patrol_map") or {}))
        .call()
    )

    set_rhino_map_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("set_rhino_map_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(var="Rhino Sightings", **(params.get("set_rhino_map_title") or {}))
        .call()
    )

    rhino_point_layer = (
        task(create_point_layer)
        .validate()
        .set_task_instance_id("rhino_point_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=rhino_colormap,
            layer_style={"get_radius": 5.0, "fill_color_column": "rhino_colormap"},
            legend={"label_column": "Rhino Name", "color_column": "rhino_colormap"},
            tooltip_columns=["Rhino Name", "time"],
            **(params.get("rhino_point_layer") or {}),
        )
        .call()
    )

    rhino_ecomap = (
        task(draw_ecomap)
        .validate()
        .set_task_instance_id("rhino_ecomap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geo_layers=rhino_point_layer,
            tile_layers=base_map_defs,
            north_arrow_style={"placement": "top-left"},
            legend_style={"title": "Rhino Name", "placement": "bottom-right"},
            static=False,
            title=None,
            max_zoom=13,
            **(params.get("rhino_ecomap") or {}),
        )
        .call()
    )

    persist_rhino_ecomap = (
        task(persist_text)
        .validate()
        .set_task_instance_id("persist_rhino_ecomap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=rhino_ecomap,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="rhino_map",
            **(params.get("persist_rhino_ecomap") or {}),
        )
        .call()
    )

    rhino_map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("rhino_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title=set_rhino_map_title,
            data=persist_rhino_ecomap,
            **(params.get("rhino_map_widget") or {}),
        )
        .call()
    )

    merged_rhino_map = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("merged_rhino_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(widgets=[rhino_map_widget], **(params.get("merged_rhino_map") or {}))
        .call()
    )

    rhino_summary = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("rhino_summary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=process_rhino,
            groupby_cols=["Rhino Name"],
            reset_index=True,
            summary_params=[
                {"display_name": "Count", "aggregator": "count", "column": "uuid"}
            ],
            **(params.get("rhino_summary") or {}),
        )
        .call()
    )

    persist_summary = (
        task(persist_df_wrapper)
        .validate()
        .set_task_instance_id("persist_summary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            df=rhino_summary,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_prefix="rhino_summary",
            filetypes=["csv"],
            sanitize=False,
            **(params.get("persist_summary") or {}),
        )
        .call()
    )

    set_table_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("set_table_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(var="Rhino Sighting Summary", **(params.get("set_table_title") or {}))
        .call()
    )

    rhino_table = (
        task(draw_table)
        .validate()
        .set_task_instance_id("rhino_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=rhino_summary,
            columns=["Rhino Name", "Count"],
            table_config={
                "enable_sorting": True,
                "enable_filtering": True,
                "enable_download": True,
                "hide_header": False,
            },
            **(params.get("rhino_table") or {}),
        )
        .call()
    )

    persist_table = (
        task(persist_text)
        .validate()
        .set_task_instance_id("persist_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=rhino_table,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="rhino_summary_table",
            **(params.get("persist_table") or {}),
        )
        .call()
    )

    table_widget = (
        task(create_table_widget_single_view)
        .validate()
        .set_task_instance_id("table_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title=set_table_title,
            data=persist_table,
            **(params.get("table_widget") or {}),
        )
        .call()
    )

    merged_table_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("merged_table_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(widgets=[table_widget], **(params.get("merged_table_widget") or {}))
        .call()
    )

    set_bar_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("set_bar_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(var="Rhino Sighting Counts", **(params.get("set_bar_title") or {}))
        .call()
    )

    rhino_bar = (
        task(draw_bar_chart)
        .validate()
        .set_task_instance_id("rhino_bar")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=rhino_summary,
            category="Rhino Name",
            layout_kwargs=None,
            bar_chart_configs=[
                {
                    "label": "Count of Sightings",
                    "column": "Count",
                    "agg_func": "sum",
                    "show_label": True,
                    "style": {"marker_color": "#35b779"},
                }
            ],
            **(params.get("rhino_bar") or {}),
        )
        .call()
    )

    persist_bar = (
        task(persist_text)
        .validate()
        .set_task_instance_id("persist_bar")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=rhino_bar,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="rhino_bar_chart",
            **(params.get("persist_bar") or {}),
        )
        .call()
    )

    bar_widget = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("bar_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title=set_bar_title, data=persist_bar, **(params.get("bar_widget") or {})
        )
        .call()
    )

    merged_bar_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("merged_bar_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(widgets=[bar_widget], **(params.get("merged_bar_widget") or {}))
        .call()
    )

    rhino_report = (
        task(create_docx)
        .validate()
        .set_task_instance_id("rhino_report")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            context={
                "items": [
                    {
                        "item_type": "timerange",
                        "key": "report_date",
                        "value": time_range,
                        "format": "%b %Y",
                    },
                    {
                        "item_type": "image",
                        "key": "patrol_map",
                        "value": persist_patrol_ecomap,
                        "screenshot_config": {
                            "wait_for_timeout": 20000,
                            "max_concurrent_pages": 2,
                            "device_scale_factor": 1.0,
                        },
                    },
                    {
                        "item_type": "image",
                        "key": "rhino_map",
                        "value": persist_rhino_ecomap,
                        "screenshot_config": {
                            "wait_for_timeout": 1000,
                            "max_concurrent_pages": 2,
                            "device_scale_factor": 1.0,
                        },
                    },
                    {
                        "item_type": "table",
                        "key": "rhino_summary",
                        "value": rhino_summary,
                    },
                    {
                        "item_type": "image",
                        "key": "bar_chart",
                        "value": persist_bar,
                        "screenshot_config": {
                            "wait_for_timeout": 0,
                            "max_concurrent_pages": 2,
                        },
                    },
                ]
            },
            groupers=[],
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_prefix="mt_rhino_report",
            **(params.get("rhino_report") or {}),
        )
        .call()
    )

    dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[
                merged_patrol_map,
                merged_rhino_map,
                merged_table_widget,
                merged_bar_widget,
            ],
            groupers=[],
            time_range=time_range,
            **(params.get("dashboard") or {}),
        )
        .call()
    )

    return dashboard
